version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pipeline_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_uY0agKRDtF9N@ep-soft-bird-anuo0mcl-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      JWT_SECRET: 7d4b6932b72de09eba64d1d548bcd62120192672ebd29bcb0969a7b7caad761fce303c4a822419a6c7c5565bd01c64f1791a0ddcb9ece63388d8c2a2ddead004
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      PORT: 8080
      NODE_ENV: development
    command: sh -c "npm run migrate && node dist/server.js"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: pipeline_worker
    restart: always
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_uY0agKRDtF9N@ep-soft-bird-anuo0mcl-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      JWT_SECRET: 7d4b6932b72de09eba64d1d548bcd62120192672ebd29bcb0969a7b7caad761fce303c4a822419a6c7c5565bd01c64f1791a0ddcb9ece63388d8c2a2ddead004
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      NODE_ENV: development
